services:
  # El backend con Laravel, Filament y SQLite
  cms-php:
    build:
      context: .
      dockerfile: Dockerfile.php
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    user: "1000:1000" # <-- Esto obliga al contenedor a ejecutar TODO como carlos
    container_name: cms_php_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    deploy:
      resources:
        limits:
          cpus: '4.0'        # Limita estrictamente a 1 núcleo de CPU
          memory: 4096M       # Limita la memoria RAM a 512 Megabytes

  # El entorno de Node.js exclusivo para Vite, Tailwind y NPM sin mezclar dependencias
  cms-node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: cms_node_assets
    volumes:
      - .:/var/www
    ports:
      - "5173:5173" # Puerto por defecto de Vite para Hot Module Replacement (HMR)
    depends_on:
      - cms-php
